using UnityEngine;

//All this code was generated by ChatGPT. I just think it's Neat!

public class MovingPiston : MonoBehaviour
{
    public float distance = 1f; // distance to move vertically
public float speed = 1f; // speed of movement
public float delay = 0f; // delay before moving back to original position
private Vector3 originalPosition; // initial position of the piston
private Vector3 targetPosition; // target position of the piston
private bool movingToTarget = true; // flag to toggle between moving to target and moving to original position
private float elapsedTime = 0f; // elapsed time since reaching target position

private void Start()
{
    originalPosition = transform.position;
    targetPosition = originalPosition + transform.up * distance;
}

private void FixedUpdate()
{
    Vector3 target = movingToTarget ? targetPosition : originalPosition;
    float step = speed * Time.fixedDeltaTime;
    transform.position = Vector3.MoveTowards(transform.position, target, step);

    if (Vector3.Distance(transform.position, target) < 0.001f)
    {
        // reached the target position, toggle flag and start delay timer
        movingToTarget = !movingToTarget;
        elapsedTime = 0f;
    }

    // if delay is set and we reached the target position, wait for delay before moving back to original position
    if (delay > 0f && !movingToTarget)
    {
        elapsedTime += Time.fixedDeltaTime;
        if (elapsedTime >= delay)
        {
            movingToTarget = true;
            elapsedTime = 0f;
        }
    }
}
}