using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//All code here is generated by ChatGPT. I just think it's neat!

public class TouchElevator : MonoBehaviour
{
    public float distance = 5f; // distance to move vertically
    public float speed = 1f; // speed of movement
    public float delay = 2f; // delay before moving back to original position
    public GameObject elevator; // reference to the elevator object
    private Vector3 originalPosition; // initial position of the elevator
    private Vector3 targetPosition; // target position of the elevator
    private bool playerInside = false; // flag to indicate whether the player is inside the collision box
    private float timer = 0f; // timer to keep track of delay

    private void Start()
    {
        originalPosition = elevator.transform.position;
        targetPosition = originalPosition + Vector3.up * distance;
    }

    private void OnTriggerEnter(Collider other)
    {
        CharacterController player = other.gameObject.GetComponent<CharacterController>();
        if (player != null)
        {
            playerInside = true;
        }
    }

    private void OnTriggerExit(Collider other)
    {
        CharacterController player = other.gameObject.GetComponent<CharacterController>();
        if (player != null)
        {
            playerInside = false;
            timer = 0f; // reset the delay timer when the player leaves the trigger box
        }
    }

    private void FixedUpdate()
    {
        Vector3 target = playerInside ? targetPosition : originalPosition;
        float step = speed * Time.fixedDeltaTime;
        elevator.transform.position = Vector3.MoveTowards(elevator.transform.position, target, step);

        if (!playerInside && timer < delay)
        {
            timer += Time.fixedDeltaTime; // start the delay timer when the player leaves the trigger box
        }
    }
}